global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
alerting:
  alertmanagers: []
rule_files: []
scrape_configs:
- job_name: prometheus
  static_configs:
    - targets:
        - "localhost:9090"
      labels:
        service: "prometheus"
