receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 15s
          static_configs:
            - targets: ["127.0.0.1:8888"] 

exporters:
  otlphttp:
    endpoint: http://localhost:9090/api/v1/otlp

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [otlphttp]
