grafana:
  enabled: true
  defaultDashboardsTimezone: browser
  adminUser: root
  adminPassword: m@ster1ngPr0m3th3us
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    enableFeatures:
      - otlp-write-receiver
    image:
      tag: v2.49.1
cleanPrometheusOperatorObjectNames: true
