name: promtool
on: push

jobs:
  config:
    name: Validate Prometheus Config
    runs-on: ubuntu-latest
    container: quay.io/prometheus/prometheus:v2.46.0
    steps:
      - name: Checkout/clone code
        uses: actions/checkout@v4

      - name: Validate Prometheus config file
        run: promtool check config ch12/prometheus.yaml

  rules:
    name: Validate Prometheus Rules
    runs-on: ubuntu-latest
    container: quay.io/prometheus/prometheus:v2.46.0
    steps:
      - name: Checkout/clone code
        uses: actions/checkout@v4

      - name: Validate Prometheus rules files
        run: promtool check rules ch12/rules/*.yaml

      - name: Run unit tests on Prometheus rules files
        run: promtool test rules ch12/tests/*.yaml
