---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app.kubernetes.io/component: "query-cache"
    app.kubernetes.io/instance: "thanos-query-frontend"
    app.kubernetes.io/name: "thanos-query-frontend"
    app.kubernetes.io/version: "v0.31.0"
  name: "thanos-query-frontend"
  namespace: "prometheus"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: "query-cache"
      app.kubernetes.io/instance: "thanos-query-frontend"
      app.kubernetes.io/name: "thanos-query-frontend"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "query-cache"
        app.kubernetes.io/instance: "thanos-query-frontend"
        app.kubernetes.io/name: "thanos-query-frontend"
        app.kubernetes.io/version: "v0.31.0"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: "In"
                  values:
                  - "thanos-query-frontend"
              namespaces:
              - "prometheus"
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      containers:
      - args:
        - "query-frontend"
        - "--log.level=info"
        - "--log.format=logfmt"
        - "--query-frontend.compress-responses"
        - "--http-address=0.0.0.0:9090"
        - "--query-frontend.downstream-url=http://thanos-query.prometheus.svc.cluster.local:9090"
        - "--query-range.split-interval=24h"
        - "--labels.split-interval=24h"
        - "--query-range.max-retries-per-request=5"
        - "--labels.max-retries-per-request=5"
        - "--query-frontend.log-queries-longer-than=60s"
        env:
        - name: "HOST_IP_ADDRESS"
          valueFrom:
            fieldRef:
              fieldPath: "status.hostIP"
        image: "quay.io/thanos/thanos:v0.31.0"
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: "/-/healthy"
            port: 9090
            scheme: "HTTP"
          periodSeconds: 30
        name: "thanos-query-frontend"
        ports:
        - containerPort: 9090
          name: "http"
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: "/-/ready"
            port: 9090
            scheme: "HTTP"
          periodSeconds: 5
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: "RuntimeDefault"
        terminationMessagePolicy: "FallbackToLogsOnError"
      nodeSelector:
        kubernetes.io/os: "linux"
      securityContext:
        fsGroup: 65534
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: "RuntimeDefault"
      serviceAccountName: "thanos-query-frontend"
      terminationGracePeriodSeconds: 120
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app.kubernetes.io/component: "query-cache"
    app.kubernetes.io/instance: "thanos-query-frontend"
    app.kubernetes.io/name: "thanos-query-frontend"
    app.kubernetes.io/version: "v0.31.0"
  name: "thanos-query-frontend"
  namespace: "prometheus"
spec:
  ports:
  - name: "http"
    port: 9090
    targetPort: 9090
  selector:
    app.kubernetes.io/component: "query-cache"
    app.kubernetes.io/instance: "thanos-query-frontend"
    app.kubernetes.io/name: "thanos-query-frontend"
---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: "query-cache"
    app.kubernetes.io/instance: "thanos-query-frontend"
    app.kubernetes.io/name: "thanos-query-frontend"
    app.kubernetes.io/version: "v0.31.0"
  name: "thanos-query-frontend"
  namespace: "prometheus"
---
apiVersion: "monitoring.coreos.com/v1"
kind: "ServiceMonitor"
metadata:
  labels:
    app.kubernetes.io/component: "query-cache"
    app.kubernetes.io/instance: "thanos-query-frontend"
    app.kubernetes.io/name: "thanos-query-frontend"
    app.kubernetes.io/version: "v0.31.0"
  name: "thanos-query-frontend"
  namespace: "prometheus"
spec:
  endpoints:
  - port: "http"
    relabelings:
    - action: "replace"
      separator: "/"
      sourceLabels:
      - "namespace"
      - "pod"
      targetLabel: "instance"
  selector:
    matchLabels:
      app.kubernetes.io/component: "query-cache"
      app.kubernetes.io/instance: "thanos-query-frontend"
      app.kubernetes.io/name: "thanos-query-frontend"
...
